package org.kate._policyservice.controller;

import jakarta.validation.Valid;
import org.kate._policyservice.model.ApiResponse;
import org.kate._policyservice.model.Policy;
import org.kate._policyservice.dto.PolicyDTO;
import org.kate._policyservice.repository.PolicyRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
@RestController
@RequestMapping("/api/v3/policies")
public class PolicyController {

    private final PolicyRepository policyRepository;

    // Manual Constructor - This fixes the red lines on policyRepository
    public PolicyController(PolicyRepository policyRepository) {
        this.policyRepository = policyRepository;
    }

    @PostMapping("/add")
    @PreAuthorize("hasAnyRole('ADMIN', 'MANAGER')")
    public ResponseEntity<ApiResponse> addPolicy(@Valid @RequestBody PolicyDTO policyDTO) {
        // 1. Check if the policy number already exists
        boolean alreadyExists = policyRepository.existsByUserIdentificationNumberAndPolicyCategory(
                policyDTO.getUserIdentificationNumber(),
                policyDTO.getPolicyCategory());
        if (alreadyExists) {
            return ResponseEntity.status(HttpStatus.CONFLICT)
                    .body(new ApiResponse(false, "User already has an active " + policyDTO.getPolicyCategory() + " policy", null));
        }
        String autoGeneratedNumber = "POL-" + java.util.UUID.randomUUID().toString().substring(0, 6).toUpperCase();

        // 2. Map DTO to Entity
        Policy policy = new Policy();
        policy.setPolicyNumber(autoGeneratedNumber);
        policy.setUserIdentificationNumber(policyDTO.getUserIdentificationNumber());
        policy.setPolicyCategory(policyDTO.getPolicyCategory());
        policy.setPremium(policyDTO.getPremium());

        // 3. Handle Date Formatting
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        policy.setExpiryDate(LocalDate.parse(policyDTO.getExpiryDate(), formatter));
        // 4. Save to Database
        Policy savedPolicy = policyRepository.save(policy);

        PolicyDTO responseDTO = new PolicyDTO(
                savedPolicy.getId(),
                savedPolicy.getPolicyNumber(),
                savedPolicy.getUserIdentificationNumber(),
                savedPolicy.getPolicyCategory(),
                savedPolicy.getPremium(),
                savedPolicy.getExpiryDate().toString()
        );
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(new ApiResponse(true, "Policy created successfully", savedPolicy));
    }

    @GetMapping("/my-policies")
    public ResponseEntity<ApiResponse> getMyPolicies(
            Authentication authentication,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {

        // 1. Extract the user's identification number from the JWT claims
        String idNumberFromToken = "";
        if (authentication.getPrincipal() instanceof org.springframework.security.oauth2.jwt.Jwt) {
            org.springframework.security.oauth2.jwt.Jwt jwt = (org.springframework.security.oauth2.jwt.Jwt) authentication.getPrincipal();
            idNumberFromToken = jwt.getClaimAsString("idNumber");
        }

        // 2. Define the pageable variable (This fixes the red "pageable" error)
        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());

        // 3. Query the policies (Change List<Policy> to Page<Policy>)
        Page<Policy> policies = policyRepository.findByUserIdentificationNumber(idNumberFromToken, pageable);

        if (policies.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ApiResponse(false, "No policies found for your account", null));
        }

        return ResponseEntity.ok(new ApiResponse(true, "Policies retrieved successfully", policies));
    }

    @GetMapping("/all-policies")
    @PreAuthorize("hasAnyRole('ADMIN')")
    public ResponseEntity<ApiResponse<Page<Policy>>> getAllPolicies(
            @RequestParam(required = false) String category,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {

        // Create a pageable object, sorting by policyNumber or ID
        Pageable pageable = PageRequest.of(page, size, Sort.by("policyNumber").ascending());
        // Fetch the paged results
        Page<Policy> policyPage;
        if (category != null && !category.isEmpty()) {
            // If admin typed a category, filter by it
            policyPage = policyRepository.findByPolicyCategory(category, pageable);
        } else {
            // If no category provided, show everything
            policyPage = policyRepository.findAll(pageable);
        }
        ApiResponse<Page<Policy>> response = new ApiResponse<Page<Policy>>(
                true,
                "Policies for user retrieved successfully",
                policyPage
        );
        return ResponseEntity.ok(response);
    }

    @GetMapping("/user/{userIdentificationNumber}")
    @PreAuthorize("hasAnyRole('ADMIN', 'MANAGER')")
    public ResponseEntity<ApiResponse<Page<Policy>>> getPoliciesByUserId(
            @PathVariable String userIdentificationNumber,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {

        Pageable pageable = PageRequest.of(page, size, Sort.by("policyNumber").ascending());

        Page<Policy> userPolicies = policyRepository.findByUserIdentificationNumber(userIdentificationNumber, pageable);

        if (userPolicies.isEmpty()) {
            ApiResponse<Page<Policy>> errorResponse = new ApiResponse<>(
                    false,
                    "No policies found for identification number: " + userIdentificationNumber,
                    null
            );
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(errorResponse);
        }

        ApiResponse<Page<Policy>> apiResponse = new ApiResponse<>(
                true,
                "Policies for user retrieved successfully",
                userPolicies
        );

        return ResponseEntity.ok(apiResponse);
    }


}


