server.port=8761
eureka.client.register-with-eureka=false

# 3. Tell the server NOT to fetch the registry from itself
eureka.client.fetch-registry=false
spring.application.name=discovery-server-service

